export const options = [
    { "value": "Mumbai", "label": "Mumbai" },
    { "value": "Delhi", "label": "Delhi" },
    { "value": "Bangalore", "label": "Bangalore" },
    { "value": "Hyderabad", "label": "Hyderabad" },
    { "value": "Chennai", "label": "Chennai" },
    { "value": "Kolkata", "label": "Kolkata" },
    { "value": "Pune", "label": "Pune" },
    { "value": "Ahmedabad", "label": "Ahmedabad" },
    { "value": "Jaipur", "label": "Jaipur" },
    { "value": "Lucknow", "label": "Lucknow" },
    { "value": "New York", "label": "New York" },
    { "value": "Los Angeles", "label": "Los Angeles" },
    { "value": "Chicago", "label": "Chicago" },
    { "value": "Houston", "label": "Houston" },
    { "value": "Phoenix", "label": "Phoenix" },
    { "value": "London", "label": "London" },
    { "value": "Manchester", "label": "Manchester" },
    { "value": "Birmingham", "label": "Birmingham" },
    { "value": "Tokyo", "label": "Tokyo" },
    { "value": "Osaka", "label": "Osaka" },
    { "value": "Kyoto", "label": "Kyoto" },
    { "value": "Paris", "label": "Paris" },
    { "value": "Lyon", "label": "Lyon" },
    { "value": "Marseille", "label": "Marseille" },
    { "value": "Berlin", "label": "Berlin" },
    { "value": "Munich", "label": "Munich" },
    { "value": "Hamburg", "label": "Hamburg" },
    { "value": "Sydney", "label": "Sydney" },
    { "value": "Melbourne", "label": "Melbourne" },
    { "value": "Brisbane", "label": "Brisbane" },
    { "value": "Moscow", "label": "Moscow" },
    { "value": "Saint Petersburg", "label": "Saint Petersburg" },
    { "value": "Novosibirsk", "label": "Novosibirsk" },
    { "value": "Beijing", "label": "Beijing" },
    { "value": "Shanghai", "label": "Shanghai" },
    { "value": "Shenzhen", "label": "Shenzhen" },
    { "value": "Rio de Janeiro", "label": "Rio de Janeiro" },
    { "value": "São Paulo", "label": "São Paulo" },
    { "value": "Brasília", "label": "Brasília" },
    { "value": "Dubai", "label": "Dubai" },
    { "value": "Abu Dhabi", "label": "Abu Dhabi" },
    { "value": "Mexico City", "label": "Mexico City" },
    { "value": "Guadalajara", "label": "Guadalajara" },
    { "value": "Buenos Aires", "label": "Buenos Aires" },
    { "value": "Córdoba", "label": "Córdoba" },
    { "value": "Cape Town", "label": "Cape Town" },
    { "value": "Johannesburg", "label": "Johannesburg" },
    { "value": "Seoul", "label": "Seoul" },
    { "value": "Busan", "label": "Busan" },
    { "value": "Singapore", "label": "Singapore" },
    { "value": "Istanbul", "label": "Istanbul" },
    { "value": "Ankara", "label": "Ankara" },
    { "value": "Rome", "label": "Rome" },
    { "value": "Milan", "label": "Milan" },
    { "value": "Bangkok", "label": "Bangkok" }
  ];

  export const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Congo (Congo-Kinshasa)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ]
  